spring.application.name=api-gateway
grpc.client.auth-service.address=static://localhost:9091
grpc.client.auth-service.negotiationType=plaintext

jwt.secret=very_secret_key_very_secret_key_1234567890
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000