syntax = "proto3";
package auction;

option java_multiple_files = true;
option java_package = "org.kowal.auction.grpc";
option java_outer_classname = "AuctionProto";

import "google/protobuf/timestamp.proto";
import "common/decimal.proto";

service AuctionService{
  rpc CreateAuction (CreateAuctionRequest) returns (AuctionResponse);
  rpc GetAuction (GetAuctionRequest) returns (AuctionResponse);
  rpc ValidateAuction (ValidateAuctionRequest) returns (ValidateAuctionResponse);
}

message CreateAuctionRequest{
  string title = 1;
  string description = 2;
  common.Decimal startPrice = 3;
  common.Decimal buyNowPrice = 4;
  common.Decimal minIncrement = 5;
  google.protobuf.Timestamp endTime = 6;
  string auctionType = 7;
  string userId = 8;
}

message AuctionResponse{
  string id = 1;
  string title = 2;
  string description = 3;
  string sellerId = 4;
  common.Decimal startPrice = 5;
  common.Decimal currentPrice = 6;
  common.Decimal buyNowPrice = 7;
  common.Decimal minIncrement = 8;
  google.protobuf.Timestamp startTime = 9;
  google.protobuf.Timestamp endTime = 10;
  string auctionStatus = 11;
  string auctionType = 12;
  google.protobuf.Timestamp createdAt = 13;
}

message GetAuctionRequest{
  string auctionId = 1;
}

message ValidateAuctionRequest {
  string auctionId = 1;
}

message ValidateAuctionResponse {
  bool valid = 1;
  string reason = 2;
  common.Decimal currentPrice = 3;
  common.Decimal minIncrement = 4;
}